title: QMK Configurator
email: david@thetemplateblog.com
show_downloads: true
description: QMK for potatoes - an open source configurator for QMK Firmware (only the AVR boards right now)
baseurl: ""
url: "https://qmk.childs.life"
github_username: thetemplateblog
repository: thetemplateblog/qmk_configurator
theme: jekyll-theme-minimal
